trigger: none

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: 'yarn'

  - script: |
      yarn build:all
    displayName: 'build'

  - script: |
      yarn test
    displayName: 'test'

  - script: |
      yarn checkchange
    displayName: 'checkchange'

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'